

    <?php echo $this->partial('metrica-asterisk/metrica-saliente-troncal/partial/table-horizontal', ['objetos' => $this->tipo->getObjetos()]); ?>

    <?php //echo $this->partial('metrica-asterisk/metrica-salientes/partial/chart-multi', ['objeto' => $objeto]); ?>

    <?php //echo $this->partial('metrica-asterisk/metrica-salientes/partial/chart-pie', ['objeto' => $objeto]); ?>

    <div class="clearfix"></div>
