<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

        <title>Central Biei</title>

        <!-- Le styles -->
        <?= $this->partial('layout/css'); ?>
        <?= $this->partial('layout/js'); ?>


    </head>
    <body class="fixed-header pace-done">
        <div id="theme-wrapper">
            <header class="navbar" id="header-navbar">
                <div class="container">
                    <a href="<?= $this->url('home'); ?>" id="logo" class="navbar-brand">
                        <img src="<?= $this->basePath() ?>/shared/centaurus/img/logo.png" alt="" class="normal-logo logo-white"/>
                        <img src="<?= $this->basePath() ?>/shared/centaurus/img/logo-black.png" alt="" class="normal-logo logo-black"/>
                        <img src="<?= $this->basePath() ?>/shared/centaurus/img/logo-small.png" alt="" class="small-logo hidden-xs hidden-sm hidden"/>
                    </a>
                    <div class="clearfix">
                        <button class="navbar-toggle" data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="fa fa-bars"></span>
                        </button>

                        <div class="nav-no-collapse navbar-left pull-left hidden-sm hidden-xs">
                            <ul class="nav navbar-nav pull-left">
                                <li>
                                    <a class="btn" id="make-small-nav">
                                        <i class="fa fa-bars"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>


                        <div class="nav-no-collapse pull-right" id="header-nav">

                            <ul class="nav navbar-nav pull-right">

                                <!--Render zf-metal/security partial menu-->
                                <?php echo $this->partial('zf-metal/security/menu/menu'); ?>

                                <li class="hidden-xxs">
                                    <a href="<?= $this->url('zf-metal.user/logout'); ?>" class="btn">
                                        <i class="fa fa-power-off"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </header>
            <div id="page-wrapper" class="container nav-small">
                <div class="row">

                    <?= $this->partial('layout/menu'); ?>

                    <div id="content-wrapper">
                        
                           <?php
                                echo $this->navigation('default')->breadcrumbs()->setMinDepth(1)
                              ->setPartial('layout/breadcrumbs');
                         ?>
                      

                        <?= $this->content; ?>

                        <?= $this->partial('layout/footer'); ?>

                    </div>
                </div>
            </div>
        </div>


    </body>
</html>